# Generated by Django 6.0.1 on 2026-04-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, upload_to='podcast_images/'),
        ),
    ]
