# Generated by Django 6.0.1 on 2026-04-02 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_page_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
