# Generated by Django 6.0.1 on 2026-04-14 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_delete_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_podcasts', to=settings.AUTH_USER_MODEL),
        ),
    ]
