# Generated by Django 6.0.1 on 2026-04-16 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_podcast_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='podcasts.podcast'),
        ),
    ]
