# Generated by Django 6.0.1 on 2026-04-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
